# Cấu hình cổng chạy riêng 8083 để tránh trùng cổng với các bài khác
server.port=8083
spring.application.name=b6_2_faculty_crud

# Tắt cache Thymeleaf để thay đổi HTML cập nhật ngay lập tức
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
