# Cổng chạy ứng dụng ôn thi giữa kỳ (8084)
server.port=8084
spring.application.name=gk_faculty_mvc

# Cấu hình Thymeleaf (tắt cache để sửa HTML là thấy ngay kết quả)
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
