# ==============================================================================
# CẤU HÌNH KẾT NỐI DATABASE MYSQL (CLEVER CLOUD)
# ==============================================================================
server.port=8080

# ------------------------------------------------------------------------------
# 1. KẾT NỐI TỚI CLEVER CLOUD MYSQL
# ------------------------------------------------------------------------------
spring.datasource.url=jdbc:mysql://bqil983hlw33dnafyqvs-mysql.services.clever-cloud.com:3306/bqil983hlw33dnafyqvs?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=un0ambnc8wmldqfb
spring.datasource.password=4YnHLJB7lYnNHrxUO26z
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ------------------------------------------------------------------------------
# 2. CẤU HÌNH HIBERNATE / JPA
# ------------------------------------------------------------------------------
# update: Tự động tạo bảng và các cột, khóa ngoại trong MySQL nếu chưa có
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL và format đẹp mắt trong Console Eclipse
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sử dụng Dialect MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Quản lý kết nối HikariCP tối ưu cho Cloud Database
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
