FROM eclipse-temurin:21-jdk-alpine AS builder
WORKDIR /build
COPY . /build
RUN javac -encoding UTF-8 *.java

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /build/*.class /app/

ENV SERVER_HOST=auction-server
ENV RMI_HOST=auction-server
ENV RMI_PORT=1099

ENTRYPOINT ["java", "AuctionClient"]
