spring.application.name=demojpa
server.port=8080

# ======================================================================
# CẤU HÌNH KẾT NỐI MYSQL LOCAL THEO HƯỚNG DẪN CỦA THẦY TRƯƠNG BÁ PHÚC
# Cài đặt tại D:\app\mysql (Port: 3306 | User: root | Pass: root)
# ======================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/b8_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================================================================
# HIBERNATE TỰ ĐỘNG SINH BẢNG CSDL TỪ ENTITY
# ======================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tắt warning open-in-view
spring.jpa.open-in-view=false
